### ISSUE TITLE
`immersive-ar` on `alpha-blend` devices with no alpha channel

### ISSUE THREAD

**Issue by cabanier** [immersive-web/webxr-ar-module#17]
The current spec allows the creation of a XRWebGLLayer with no [alpha](https://immersive-web.github.io/webxr/#ref-for-dom-xrwebgllayerinit-alpha).

This results in the entire scene being treated as opaque so the real world is no longer visible. Should we say that a session can't be created unless it has alpha for an `immersive-ar` session on `alpha-blend` devices?

**Comment by Manishearth** [comment]
The layer is not set during creation. We could potentially throw an error in updateRenderState however.

**Comment by Manishearth** [comment]
Oh, wait, we can throw earlier, in the XRWebGLLayer creation algorithm.

**Comment by cabanier** [comment]
I think it should. What do you think @toji ?

**Comment by toji** [comment]
Gave some thought to this over the last week, and my opinion is that **we probably shouldn't apply any restriction to when a layer does or doesn't require alpha.**

Considerations that go into that opinion:

- If we were going to start enforcing something like that it would be best to just pick the "right" alpha state for any given session, but that seems problematic.
- Obviously alpha doesn't really have much visual affect single-layer, `opaque` systems, but we should allow it regardless since it'll make the transition to multi-layer rendering easier and in the meantime there's potential for developers to use the alpha channel as data storage.
- With AR sessions developers may still want to turn off alpha when dealing with an additive display as a potential performance boost. But we don't necessarily want to prevent it from using alpha either for the reasons listed above.
- There's a legitimate concern that if we don't force alpha on for all AR headsets then devs will test on an `additive` display and say "it works!" and ship a broken experience to users of `alpha-blend` displays. However, throwing an error only in the `alpha-blend` case will still cause a failure that the developer doesn't notice, just a different type of error that produces zero working content instead of partially working content. The only way we avoid it is requiring alpha for _all_ `immersive-ar` sessions, and we don't want that because of the aforementioned performance considerations on `additive`.
- Finally, it's been brought up in the past that some developers may want to use AR tracking for a fully virtual scene on handsets, or potentially switch back and forth between AR/VR on an `alpha-blend` headset without destroying the session. In that case switching to a layer that has no alpha channel could function as a signal to the UA that the video stream no longer needs to be composited, offering a significant performance win.

Effectively it boils down to: It's hard to protect developers from themselves if they're going to be lazy about testing, but there's legitimate reasons for offering flexibility here.
