### ISSUE TITLE
Should handheld and headset AR use the same XRSessionMode?

### ISSUE THREAD

**Issue by ddorwin** [immersive-web/webxr-ar-module#29]
The current plan is that both handheld (e.g., smartphone) AR and headset AR will be accessed via the `"immersive-ar"` `XRSessionMode`. The intent is that applications written for one form factor will also work on the other, enabling as many clients and users as possible to experience AR content.

On the other hand:
1. It's arguable that sessions for AR and VR headsets have more in common than do handheld and headset AR (i.e., #28).
1. The (ideal) interaction and UI for handheld and headset AR are likely to be different.
   * i.e., #9.
   * This is a topic of discussion in [DOM Overlays](https://github.com/immersive-web/dom-overlays).
1. Other areas of WebXR are currently diverging from such progressive enhancement/fallback (#27).

This issue tracks deciding whether and how sessions for handheld and headset AR are related. It likely makes sense to resolve #27 first. #28 may also affect this issue if there is no longer a distinction between immersive AR and VR sessions and the question thus becomes whether handheld AR is "immersive." Can the API design and affordances mentioned in that issue also address the difference in AR form factors? (See https://github.com/immersive-web/webxr/issues/786#issuecomment-520478339 for some examples of the preferences a developer might want to convey.)

Regardless of the specific outcome, hopefully there will continue to be a fallback path where all AR devices can at least _access_ most AR content even if, for example, the UI is not ideal.

**Comment by blairmacintyre** [comment]
(many of us can't go to the facetoface so I'd like to keep the discussion visible, please)

I'm against separate modes.  We must be able to detect which setup is being used (handheld or headmount, and perhaps others like projection) so that we can adapt, of course.

I do not see how having separate modes can achieve this last paragraph:
> Regardless of the specific outcome, hopefully there will continue to be a fallback path where all AR devices can at least access most AR content even if, for example, the UI is not ideal.

Separate modes pretty much guarantees large amounts of content that only works in one or the other.

Right now on the 2D web, we have some sites that only support desktop well, but those are accessible on mobile because no "work" is required on the part of the site to support that.  The proportion of desktop only sites is falling, though, largely because frameworks make it easy to support both.  One could argue that here, a framework would support both "modes", but on the other hand, a framework can also support creating different UIs for both kinds of devices.

**Comment by rcabanier** [comment]
> (many of us can't go to the facetoface so I'd like to keep the discussion visible, please)

Can you call in? I believe WebEx will be available and there will be a queue so you won't be skipped.

> ...
> Right now on the 2D web, we have some sites that only support desktop well, but those are accessible on mobile because no "work" is required on the part of the site to support that. The proportion of desktop only sites is falling, though, largely because frameworks make it easy to support both. 

There is still a large number of sites that do UA sniffing and then redirect or return content catered for a specific device (ie google.com). This is something we must avoid.
If the spec won't allow selection of a specific form factor, the site is going to do it for us (which locks out less popular UA's and devices)

> One could argue that here, a framework would support both "modes", but on the other hand, a framework can also support creating different UIs for both kinds of devices.

I think `sessionSupported` gives frameworks a clean way to detect features ahead of entering immersive. Having to do it after the fact seems error prone.

**Comment by blairmacintyre** [comment]
I can't call in, no.

**Comment by Manishearth** [comment]
This was discussed at the face to face.

The conclusion made was to not do this for now. Modes are useful if a device supports both and we want to give the user the ability to pick, before the session starts. It sounds unlikely for a device that supports handheld _and_ headworn AR to exist.

@klausw brought up that, in general, modes are quite coarse anyway -- we don't distinguish between support for 6dof/3dof, bounded/unbounded in the mode. So we're unlikely to add more modes for now.

We _very much do_ want to support the ability to distinguish between handheld and headworn AR _once the session has begun_ so that you can draw things, and that's  #9. I'm super interested in hearing opinions on how to accomplish that there!

If we end up in a situation where there is a device which supports both handheld and headworn (I can imagine a cardboard-like with a passthrough camera), or if people would like the ability to design applications which _only_ work on handheld (or headworn) AR, we could potentially use the "features" feature to have ways of forcing this. If we do this can also allow user agents to give the user the ability to override this in settings and allow headworn experiences for handheld devices and vice versa.

**Comment by rcabanier** [comment]
@Manishearth Can you point to the minutes where it was decided to close this?
I don't recollect that there was agreement on this

**Comment by Manishearth** [comment]
I thought we did, but it's not in the minutes. Are there any leftover concerns not addressed by my comment above? It didn't seem like people had more to say after that. I'll reopen for now, and we can close if there's not any further development.

**Comment by Manishearth** [comment]
/agenda We should discuss this alongside #9 and #28 as a general discussion about modes

**Comment by Manishearth** [comment]
We discussed this a bit and it seemed like folks were more eager for a good solution for #9 instead of frontloading the choice (and potentially making certain content needlessly inaccessible to other devices)

**Comment by AdaRoseCannon** [comment]
Removing the agenda label since it has been closed.
